import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Button } from '@aws-amplify/ui-react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Chinedu Next on Amplify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Link href='protected-page' passHref><Button variation='warning' style={{ maxWidth: '300px' }}>View Protected Page</Button></Link>
      </nav>

      <main id="main">

      </main>
      <footer>
        <p>Some Dummy content would go here</p>

      </footer>
      <p className="copyright">
        &copy; Chinedu Ukpe 2021
      </p>
    </>
  )
}
