import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { Button } from '@aws-amplify/ui-react';
import { S3 } from 'aws-sdk';
import { useEffect, useState } from 'react';
import { useMotionValue } from 'framer-motion';
import { v4 as uuidv4 } from 'uuid';
import ReactLoader from 'react-loader';

const s3Client = new S3({
  accessKeyId: process.env.NEXT_PUBLIC_AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.NEXT_PUBLIC_AWS_SECRET,
  region: 'eu-west-1',
});

export default function Home() {
  const [fileToUpload, setFileToUpload] = useState(null);
  const [loading, setLoading] = useState(false);
  const [upload, setUpload] = useState(null);
  const progress = useMotionValue();
  const [uploadProgress, setUploadProgress] = useState(0);

  useEffect(() => {
    progress.set(0);
    setUpload(null);
  }, [fileToUpload]);
  useEffect(() => {
    return upload?.abort();
  }, []);

  const handleSubmit = async () => {
    if (!fileToUpload) return;
    try {
      setLoading(true);
      const params = {
        Bucket: process.env.NEXT_PUBLIC_S3_BUCKET,
        Key: `${uuidv4()}-${fileToUpload.name}`,
        Body: fileToUpload,
        apiVersion: '2006-03-01',
        Region: 'us-east-1',
      };

      const upload = s3Client.upload(params);
      upload.on('httpUploadProgress', (p) => {
        console.log(p.loaded / p.total);
        progress.set(p.loaded / p.total);
        setUploadProgress(p.loaded / p.total);
      });
      const uploadData = await upload.promise();
      console.log(uploadData);
      console.log(`File uploaded successfully: ${fileToUpload.name}`);
    } catch (error) {
      console.log(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Profit Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Upload Progress:{' '}
          <Link href="https://nextjs.org">
            {((uploadProgress ?? 0) * 100).toFixed(0)}
          </Link>
        </h1>

        <p className={styles.description}>
          Get started by <code className={styles.code}>Signing up</code>
        </p>

        <div>
          <input
            type="file"
            onChange={(e) => setFileToUpload(e.target.files[0])}
          />
          {/* <Link href="/dashboard" passHref> */}
          <Button onClick={handleSubmit} variation="primary">
            {loading ? <ReactLoader /> : 'Upload file'}
          </Button>
          {/* </Link> */}
        </div>
      </main>
    </div>
  );
}
